services:
  request-broker-service:
    build:
      context: ..\erp-request-broker
      dockerfile: .\request-broker.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  user-service:
    build:
      context: ..\erp-user-service
      dockerfile: .\user-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      JWT_KEY: AGIswjd18who8hsOQHso1akdni2oh182
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - "6379:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - ./db-data/redis/data:/root/redis
      - ./db-data/redis/redis.conf:/usr/local/etc/redis/redis.conf